backend:
  name: github
  branch: master
  base_url: https://sduduzog.com
  repo: sduduzog/sduduzog.github.io
  auth_endpoint: api/begin

local_backend: true

media_folder: static/img
public_folder: /img
publish_mode: editorial_workflow
collections:
  - name: "blog"
    label: "Blog"
    format: "frontmatter"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: false,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          required: false,
        }
      - label: "Cover Image"
        name: "coverImage"
        widget: "image"
        required: false
        media_library:
          config:
            multiple: false
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "projects"
    label: "Projects"
    format: "frontmatter"
    folder: "content/projects"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
