backend:
  name: git-gateway
  branch: master

local_backend: true
media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    format: 'json'
    folder: 'assets/content/blog'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - {
          label: 'Published',
          name: 'published',
          widget: 'boolean',
          default: false,
        }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['dev'] }
      - { label: 'Description', name: 'description', widget: 'string' }
      - {
          label: 'Cover Image',
          name: 'image',
          widget: 'image',
          required: false,
          media_library: { config: { multiple: false } },
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'project'
    label: 'Project'
    format: 'json'
    folder: 'assets/content/projects'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Live', name: 'live', widget: 'boolean', default: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Repo', name: 'repo', widget: 'string' }
      - {
          label: 'Description',
          name: 'body',
          widget: 'markdown',
          required: false,
        }
